spring:
  application:
    name: product-service

server:
  port: 7070
# additional ports 7071 6071
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
